[background-color="#01303a"]
== What powers the Kotlin DSL

=== Gradle <--> Kotlin

* Gradle provides a dynamic model that
** ... can be configured by build authors
** ... can be extended by plugin authors
* The Kotlin DSL provides
** ... a statically typed facade on top of that model
** ... support for authoring builds
** ... the complete Gradle feature set

=== Kotlin idioms in the DSL

* Delegated Properties
* Extension functions
* Implicit receivers

=== Delegated Properties

Delegated properties are syntactic sugar for accessing values of a certain type.
Values can be accessed using the `by` keyword if the containing object implements:

[source,kotlin]
----
fun getValue(thisRef: Any?, property: KProperty<*>): T
----

This works for example for Maps:

[source,kotlin]
----
val map = mapOf("name" to "Benedikt")
val name: String by map
println(name) // prints "Benedikt"
----

=== Delegated Properties in Gradle

`build.gradle.kts`
[source,kotlin]
----
val myTask = tasks.register<Copy>("myTask") {
    // configure copy
}
----

vs.

`build.gradle.kts`
[source,kotlin]
----
val myTask: Copy by tasks.registering {
    // configure copy
}
----

=== Delegated Properties in Gradle

Works with all `DomainObjectContainers`

`build.gradle.kts`
[source,kotlin]
----
val integTest: SourceSet by sourceSets.creating {
    compileClasspath = files(configurations.compileClasspath)
    runtimeClasspath = files(configurations.runtimeClasspath)
}

val optionalDeps: Configuration by configurations.creating {
    isCanBeResolved = true
    isCanBeConsumed = false
}
----

=== Extension functions

Extend any class with additional functionality:

`StringExtensions.kt`
[source,kotlin]
----
fun String.capitalize() {
    // go through this string and make first characters upper case
}
----

`SomeClass.kt`
[source,kotlin]
----
import capitalize

fun someMethod(str: String)
    str.capitalize()
}
----

=== Extension functions in Gradle

`build.gradle.kts`
[source,kotlin]
----
plugins {
    java
}

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

tasks.test {
    useJUnitPlatform()
}
----

=== Extension functions in Gradle

`build.gradle.kts`
[source,kotlin]
----
plugins {
    java // where is this coming from?
}

java { // where is this coming from?
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

tasks.test {  // where is test coming from?
    useJUnitPlatform()
}
----

=== Extension functions in Gradle

Somewhere inside the Kotlin DSL implementation (simplified)

`build.gradle.kts`
[source,kotlin]
----
val org.gradle.plugin.use.PluginDependenciesSpec.`java`

fun org.gradle.api.Project.java(configure: Action<JavaPluginExtension>)

val org.gradle.api.TaskContainer.`test`: TaskProvider<Test>
----

DSL extensions for plugins that are added to the build are generated on the fly!

=== Receivers in Kotlin

The receiver of a call is the object the call will executed against.

[source,kotlin]
----
class Guitar {

    fun playTune() { }

    fun playSong(): {
        playTune() // implicit receiver
        this.playTune() // explicit receiver
    }
}
----

=== Implicit receivers in Gradle

Let's take a step back and think about build scripts again...

`build.gradle.kts`
[source,kotlin]
----
tasks.test {
    useJUnitPlatform()
}
----

* Where is `tasks` coming from?
* Who is the receiver of the `useJUnitPlatform()` call?

=== Inside Kotlin build scripts...

* Project is set as an implicit receiver
* All types from the Gradle API are implicitly imported
* Configuration lambdas have an implicit receiver of the type that is configured

`build.gradle.kts`
[source,kotlin]
----
project.tasks.test { test ->
    test.useJUnitPlatform()
}
----
